spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update #第一次建表create，后面update
    show-sql: true
